<?php

namespace TNTExpressConnect\Price\XSD;

/**
 * Class representing Document
 */
class Document
{

    /**
     * The requestId is a unique identifier for your price request which should be
     * provided to
     *  the agent when
     *  contacting the service centre with any queries you have about the
     * ExpressConnect pricing
     *  service. It will allow
     *  quick recovery of the request and response XML and enable a more timely
     * response to
     *  any enquiry.
     *
     * @property string $requestId
     */
    private $requestId = null;

    /**
     * This provides a breakdown of any errors or warning generated by the request.
     *
     * @property \TNTExpressConnect\Price\XSD\ErrorsType $errors
     */
    private $errors = null;

    /**
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @property \TNTExpressConnect\Price\XSD\PriceResponseType[] $priceResponse
     */
    private $priceResponse = array(
        
    );

    /**
     * Gets as requestId
     *
     * The requestId is a unique identifier for your price request which should be
     * provided to
     *  the agent when
     *  contacting the service centre with any queries you have about the
     * ExpressConnect pricing
     *  service. It will allow
     *  quick recovery of the request and response XML and enable a more timely
     * response to
     *  any enquiry.
     *
     * @return string
     */
    public function getRequestId()
    {
        return $this->requestId;
    }

    /**
     * Sets a new requestId
     *
     * The requestId is a unique identifier for your price request which should be
     * provided to
     *  the agent when
     *  contacting the service centre with any queries you have about the
     * ExpressConnect pricing
     *  service. It will allow
     *  quick recovery of the request and response XML and enable a more timely
     * response to
     *  any enquiry.
     *
     * @param string $requestId
     * @return self
     */
    public function setRequestId($requestId)
    {
        $this->requestId = $requestId;
        return $this;
    }

    /**
     * Gets as errors
     *
     * This provides a breakdown of any errors or warning generated by the request.
     *
     * @return \TNTExpressConnect\Price\XSD\ErrorsType
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Sets a new errors
     *
     * This provides a breakdown of any errors or warning generated by the request.
     *
     * @param \TNTExpressConnect\Price\XSD\ErrorsType $errors
     * @return self
     */
    public function setErrors(\TNTExpressConnect\Price\XSD\ErrorsType $errors)
    {
        $this->errors = $errors;
        return $this;
    }

    /**
     * Adds as priceResponse
     *
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @return self
     * @param \TNTExpressConnect\Price\XSD\PriceResponseType $priceResponse
     */
    public function addToPriceResponse(\TNTExpressConnect\Price\XSD\PriceResponseType $priceResponse)
    {
        $this->priceResponse[] = $priceResponse;
        return $this;
    }

    /**
     * isset priceResponse
     *
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @param scalar $index
     * @return boolean
     */
    public function issetPriceResponse($index)
    {
        return isset($this->priceResponse[$index]);
    }

    /**
     * unset priceResponse
     *
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @param scalar $index
     * @return void
     */
    public function unsetPriceResponse($index)
    {
        unset($this->priceResponse[$index]);
    }

    /**
     * Gets as priceResponse
     *
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @return \TNTExpressConnect\Price\XSD\PriceResponseType[]
     */
    public function getPriceResponse()
    {
        return $this->priceResponse;
    }

    /**
     * Sets a new priceResponse
     *
     * This element provides the pricing information that is returned per priceCheck
     * request.
     *  There may be up to a maximum of 10 priceResponse
     *
     * @param \TNTExpressConnect\Price\XSD\PriceResponseType[] $priceResponse
     * @return self
     */
    public function setPriceResponse(array $priceResponse)
    {
        $this->priceResponse = $priceResponse;
        return $this;
    }


}

